# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Shared GH Actions"
  homepage: https://maven.apache.org/
  labels:
    - java
    - build-management
    - apache-maven
    - maven
    - hacktoberfest
